# the time at which the image containing the classification was captured
builtin_interfaces/Time stamp

# output of classification for each resnset 18 classifier
Resnet18ClassifierObservation[] classifier_observations

string RESNET18_SEVERE_HEMORRHAGE='RESNET18_SEVERE_HEMORRHAGE'
string RESNET18_TRAUMA_HEAD='RESNET18_TRAUMA_HEAD'
string RESNET18_TRAUMA_TORSO='RESNET18_TRAUMA_TORSO'
string RESNET18_TRAUMA_UPPER_EXTREMITY='RESNET18_TRAUMA_UPPER_EXTREMITY'
string RESNET18_TRAUMA_LOWER_EXTREMITY='RESNET18_TRAUMA_LOWER_EXTREMITY'
string RESNET18_ALERTNESS_OCULAR='RESNET18_ALERTNESS_OCULAR'